// <auto-generated />
using System;
using BookstoreApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookstoreApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260104180704_v3")]
    partial class v3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("Birthday");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "Jugoslovenski pisac, dobitnik Nobelove nagrade za književnost 1961. godine. Najpoznatiji po romanima o Bosni.",
                            DateOfBirth = new DateTime(1892, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Ivo Andrić"
                        },
                        new
                        {
                            Id = 2,
                            Biography = "Bosanskohercegovački i jugoslovenski pisac. Najpoznatiji po romanu 'Derviš i smrt'.",
                            DateOfBirth = new DateTime(1910, 4, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Meša Selimović"
                        },
                        new
                        {
                            Id = 3,
                            Biography = "Srpski romanopisac i političar, autor velikih romanesknih ciklusa o srpskoj istoriji.",
                            DateOfBirth = new DateTime(1921, 12, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Dobrica Ćosić"
                        },
                        new
                        {
                            Id = 4,
                            Biography = "Srpski pesnik, prozni pisac i književni istoričar. Najpoznatiji po romanu 'Hazarski rečnik'.",
                            DateOfBirth = new DateTime(1929, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Milorad Pavić"
                        },
                        new
                        {
                            Id = 5,
                            Biography = "Jugoslovenski pisac jevrejskog porekla, jedan od najznačajnijih autora 20. veka.",
                            DateOfBirth = new DateTime(1935, 2, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Danilo Kiš"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<int>("AwardId")
                        .HasColumnType("integer");

                    b.Property<int>("YearAwarded")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "AwardId");

                    b.HasIndex("AwardId");

                    b.ToTable("AuthorAwardBridge", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            AwardId = 1,
                            YearAwarded = 1961
                        },
                        new
                        {
                            AuthorId = 1,
                            AwardId = 2,
                            YearAwarded = 1954
                        },
                        new
                        {
                            AuthorId = 1,
                            AwardId = 3,
                            YearAwarded = 1982
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 2,
                            YearAwarded = 1966
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 3,
                            YearAwarded = 1985
                        },
                        new
                        {
                            AuthorId = 2,
                            AwardId = 4,
                            YearAwarded = 1990
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 2,
                            YearAwarded = 1962
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 3,
                            YearAwarded = 1981
                        },
                        new
                        {
                            AuthorId = 3,
                            AwardId = 4,
                            YearAwarded = 1988
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 2,
                            YearAwarded = 1985
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 3,
                            YearAwarded = 1990
                        },
                        new
                        {
                            AuthorId = 4,
                            AwardId = 4,
                            YearAwarded = 1991
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 2,
                            YearAwarded = 1973
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 3,
                            YearAwarded = 1987
                        },
                        new
                        {
                            AuthorId = 5,
                            AwardId = 4,
                            YearAwarded = 1989
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YearOfFirstAssignment")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Awards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Najpoznatija književna nagrada na svetu, dodeljena za izuzetan doprinos svetskoj književnosti.",
                            Name = "Nobelova nagrada za književnost",
                            YearOfFirstAssignment = 1901
                        },
                        new
                        {
                            Id = 2,
                            Description = "Prestižna srpska književna nagrada za najbolji roman godine, dodeljena od strane lista NIN.",
                            Name = "NIN nagrada",
                            YearOfFirstAssignment = 1954
                        },
                        new
                        {
                            Id = 3,
                            Description = "Srpska književna nagrada za najbolju pripovetku ili roman.",
                            Name = "Andrićeva nagrada",
                            YearOfFirstAssignment = 1981
                        },
                        new
                        {
                            Id = 4,
                            Description = "Međunarodna književna nagrada za izuzetan doprinos evropskoj književnosti.",
                            Name = "Evropska književna nagrada",
                            YearOfFirstAssignment = 1985
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PublisherId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "978-86-01-00001-1",
                            PageCount = 352,
                            PublishedDate = new DateTime(1945, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Na Drini ćuprija"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "978-86-01-00002-8",
                            PageCount = 288,
                            PublishedDate = new DateTime(1942, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Travnička hronika"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            ISBN = "978-86-01-00003-5",
                            PageCount = 176,
                            PublishedDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Prokleta avlija"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            ISBN = "978-86-01-00004-2",
                            PageCount = 368,
                            PublishedDate = new DateTime(1966, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Derviš i smrt"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 2,
                            ISBN = "978-86-01-00005-9",
                            PageCount = 312,
                            PublishedDate = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Tvrđava"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 3,
                            ISBN = "978-86-01-00006-6",
                            PageCount = 624,
                            PublishedDate = new DateTime(1954, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Koreni"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 3,
                            ISBN = "978-86-01-00007-3",
                            PageCount = 544,
                            PublishedDate = new DateTime(1961, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Deobe"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 3,
                            ISBN = "978-86-01-00008-0",
                            PageCount = 1200,
                            PublishedDate = new DateTime(1972, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 1,
                            Title = "Vreme smrti"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 4,
                            ISBN = "978-86-01-00009-7",
                            PageCount = 336,
                            PublishedDate = new DateTime(1984, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Hazarski rečnik"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 4,
                            ISBN = "978-86-01-00010-3",
                            PageCount = 192,
                            PublishedDate = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 2,
                            Title = "Predeo slikan čajem"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 5,
                            ISBN = "978-86-01-00011-0",
                            PageCount = 264,
                            PublishedDate = new DateTime(1965, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Bašta, pepeo"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 5,
                            ISBN = "978-86-01-00012-7",
                            PageCount = 144,
                            PublishedDate = new DateTime(1976, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = 3,
                            Title = "Grobnica za Borisa Davidoviča"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Terazije 16, Beograd",
                            Name = "Prosveta",
                            Website = "https://www.prosveta.rs"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Resavska 33, Beograd",
                            Name = "Laguna",
                            Website = "https://www.laguna.rs"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Makedonska 30, Beograd",
                            Name = "Vulkan izdavaštvo",
                            Website = "https://www.vulkanizdavastvo.rs"
                        });
                });

            modelBuilder.Entity("BookstoreApplication.Models.AuthorAward", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Award", "Award")
                        .WithMany("AuthorAwards")
                        .HasForeignKey("AwardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Award");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Book", b =>
                {
                    b.HasOne("BookstoreApplication.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookstoreApplication.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Author", b =>
                {
                    b.Navigation("AuthorAwards");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Award", b =>
                {
                    b.Navigation("AuthorAwards");
                });

            modelBuilder.Entity("BookstoreApplication.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
